name: Release canary
on:
  push:
    branches:
      - master
jobs:
  publish_package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Resolve yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache 
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install global packages
        run: npm install -g lerna

      - name: Install dependencies
        run: lerna bootstrap -- --frozen-lockfile

      - name: Build, test, and publish the package
        run: |
          lerna publish \
            --canary \
            --preid alpha \
            --pre-dist-tag alpha \
            --message 'ci: Release %s'
