name: "Verify"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@atweel' # Defaults to the user or organization that owns the workflow file
      - run: yarn install
      - run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ORG_READER_TOKEN }}